// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	logpoller "github.com/smartcontractkit/chainlink-solana/pkg/solana/logpoller"
	mock "github.com/stretchr/testify/mock"
)

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

type Parser_Expecter struct {
	mock *mock.Mock
}

func (_m *Parser) EXPECT() *Parser_Expecter {
	return &Parser_Expecter{mock: &_m.Mock}
}

// ProcessEvent provides a mock function with given fields: _a0
func (_m *Parser) ProcessEvent(_a0 logpoller.ProgramEvent) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ProcessEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(logpoller.ProgramEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Parser_ProcessEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessEvent'
type Parser_ProcessEvent_Call struct {
	*mock.Call
}

// ProcessEvent is a helper method to define mock.On call
//   - _a0 logpoller.ProgramEvent
func (_e *Parser_Expecter) ProcessEvent(_a0 interface{}) *Parser_ProcessEvent_Call {
	return &Parser_ProcessEvent_Call{Call: _e.mock.On("ProcessEvent", _a0)}
}

func (_c *Parser_ProcessEvent_Call) Run(run func(_a0 logpoller.ProgramEvent)) *Parser_ProcessEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logpoller.ProgramEvent))
	})
	return _c
}

func (_c *Parser_ProcessEvent_Call) Return(_a0 error) *Parser_ProcessEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Parser_ProcessEvent_Call) RunAndReturn(run func(logpoller.ProgramEvent) error) *Parser_ProcessEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewParser creates a new instance of Parser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Parser {
	mock := &Parser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
